<?php

namespace Pascal\ShopTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository {

	public function showProductsInUserCart() {
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM PascalShopTestBundle:Product p'
			)
			->getResult();
	}



}
