<?php

namespace Pascal\ShopTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCartRepository extends EntityRepository
{
}
